export const ADD_BOOK = 'ADD_BOOK'
export const DELETE_BOOK = 'DELETE_BOOK'
export const BOOK_SELECTED = 'BOOK_SELECTED'
export const ADD_NOTE = 'ADD_NOTE'
export const DELETE_ALL='DELETE_ALL'
export const NOTE_SELECTED='NOTE_SELECTED'
export const DELETE_NOTE='DELETE_NOTE'
